name: dart_wait_concurrently
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/saibotma/dart_wait_concurrently

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
